name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4
      - name: Select Xcode
        run: |
          echo "Selecting Xcode 16.4"
          sudo xcode-select -s /Applications/Xcode_16.4.app/Contents/Developer || true
      - name: Use Makefile for CI
        run: make ci
