name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install Swift
        uses: fwal/setup-swift@v2
        with:
          swift-version: '5.9'
      - name: Use Makefile for CI
        run: make ci
