name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4
      - name: Select Xcode
        uses: actions/setup-xcode@v3
        with:
          xcode-version: '16.4'
      - name: Use Makefile for CI
        run: make ci
